name: "Generate github issues"
description: "generate github issues from csv"

inputs:
  token:
    description: "Token for allowing the action to create issues"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Print CSV
      run: |
        import csv
        with open('controls.csv', 'r') as file:
          reader = csv.reader(file)
          for row in reader:
            print(', '.join(row))
      shell: python
