name: "Generate github issues"
description: "generate github issues from csv"

inputs:
  token:
    description: "Token for allowing the action to create issues"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - run: pip install requests
      shell: bash
      
    - name: Print CSV
      run: |
        import csv
        import requests
        with open('controls.csv', 'r') as file:
          reader = csv.reader(file)
          next(reader)
          next(reader)
          row = reader[0]
          #for row in reader:
            #print(', '.join(row))
          url = "https://api.github.com/repos/ascheid/itsg33-pbmm-issue-gen/issues"
          header = { "Accept": "application/vnd.github+json",
                     "Authorization": "Bearer ${{ inputs.token }}",
                     "X-GitHub-Api-Version": "2022-11-28"
          }
          title = "{}-{} {}".format(row[0], row[1], row[3])
          body = "{}".format(row[5])
          labels = ["ITSG33"]
          json = {"title": title, "body": body, "labels": labels}
          r = requests.post(url, data=json, headers=headers)
          print(r.text)
      shell: python
